# Generated by Django 2.0.2 on 2018-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
